
name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@667'
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@june07'
      - run: npm ci
      - run: echo "registry=https://npm.pkg.github.com" >> .npmrc
      - run: |
          node <<EOF
            const fs = require('fs').promises;
            fs.readFile('package.json', 'utf8').then(data => JSON.parse(data)).then(json => {
              console.log(json);
                json.name = json.name.replace('@667', '@june07');
                console.info('Package name changed to %s', json.name);
                return fs.writeFile('package.json', JSON.stringify(json), 'utf8');
            }).catch(error => {
                console.error(error);
                process.exit(1);
            });
          EOF
      - run: npm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}