name: Publish npm Package

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build  # Replace with your build command
      - name: Login to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm login --registry=https://registry.npmjs.org/ --legacy-peer-deps
      - name: Publish package
        run: npm publish
